### ISSUE TITLE
Plugin crashes intermittently during upload

### ISSUE THREAD

**Issue by adityakhatkhate** [microsoft/fastlane-plugin-appcenter#163]
Hi @jp-andre and team,

We are noticing that uploads to App Center are intermittently failing. Below is the error we see when we tried to upload a unity windows build to app center. If we try again it succeeds. It would be great, if there could be a retry option with a retry count. 

```
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [31m[!] Internal Service Error, please try again later[0m (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.6.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:246:in `update_release_upload'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.6.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:214:in `upload_build'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.6.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:184:in `run_release_upload'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.6.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:266:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:280:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Thanks.

**Comment by dharapatel06** [comment]
Any update on this? facing the same issue with version 1.8.0

**Comment by kxl6767** [comment]
also facing the same issue

**Comment by darrengyl** [comment]
facing the same issue recently

**Comment by muehlemann** [comment]
facing this issue as well

**Comment by ZackOPP** [comment]
Facing same issue here. Updating to the latest version gives me another error:

```
Error fetching information about release 504: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.10</center>
</body>
</html>
```

From what I see in [appcenter_upload_action.rb](https://github.com/microsoft/fastlane-plugin-appcenter/blob/2b8aef1aa9a75faf09f14428d50d65d9d35b34e7/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L227), you guys need to fetch the release Id in order to set the "release notes" and the destination. But it's getting timeout while calling: "v0.1/apps/#{owner_name}/#{app_name}/uploads/releases/#{upload_id}"

Is there a fix that can be done from your side (or ours) or we need to wait for AppCenter until they fix their API?

microsoft/appcenter#2069

**Comment by ZackOPP** [comment]
It has been fixed by AppCenter 🎉 

https://status.appcenter.ms/

**Comment by adityakhatkhate** [comment]
@ZackOPP This ticket is specifically to provide a retry functionality with a retry count as part of the appcenter upload process so intermittent issues do not cause pipeline failures (sometimes appcenter is seen to give a 500 error for one call but the next time you call the end point it works).

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
