### ISSUE TITLE
Cannot create Custom apps with no platform

### ISSUE THREAD

**Issue by lacostej** [microsoft/fastlane-plugin-appcenter#205]
```
NoMethodError: [!] undefined method `length' for nil:NilClass
  /Users/adminwwtk/jenkins/workspace/game_Persistence-feature_new_persistence_layer_linux/.bundle/ruby/2.5.0/bundler/gems/fastlane-plugin-appcenter-ab3f8b74ac0e/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:277:in `get_or_create_app'
  /Users/adminwwtk/jenkins/workspace/game_Persistence-feature_new_persistence_layer_linux/.bundle/ruby/2.5.0/bundler/gems/fastlane-plugin-appcenter-ab3f8b74ac0e/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:296:in `run'
```

**Comment by ajaykn** [comment]
Thanks @lacostej for logging the issue.
Yeah looks like this is an unhanded bug.

Do you still see an issue if you pass in your fast file.
`app_os: 'Custom',
  app_platform: 'Custom',`

**Comment by lacostej** [comment]
@ajaykn I sent a PR 9 days ago. See #206

**Comment by ajaykn** [comment]
@lacostej Thanks for raising the PR, we have team looking into this and will be soon updated.

**Comment by jp-andre** [comment]
See also #216, simpler.
