### ISSUE TITLE
Increase upload limit

### ISSUE THREAD

**Issue by tundsD53** [microsoft/fastlane-plugin-appcenter#219]
I seem to be getting a "broken pipe" error when trying to upload my build to appcentre, currently the ipa Is sitting at 5.5GB & works with the old hockey action, but there's always a fear this will get deprecated. Is there anyway to define a higher file size when uploading? Just to show the output of the issue.

```
	[Step 1/1] /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:322:in `syswrite': [!] Broken pipe (Faraday::ConnectionFailed)
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:322:in `do_write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:339:in `block in write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `each'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `inject'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:207:in `copy_stream'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:207:in `send_request_with_body_stream'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:125:in `exec'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1507:in `block in transport_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1479:in `request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1470:in `request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:87:in `perform_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/request/url_encoded.rb:15:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/request/multipart.rb:15:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:175:in `post'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:203:in `upload_build'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:193:in `run_release_upload'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:297:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[15:30:14]	[Step 1/1] from extensions/AppCenterFastfile:7:in `block (2 levels) in parsing_binding'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane.rb:33:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[15:30:14]	[Step 1/1] from Fastfile:51:in `block (2 levels) in parsing_binding'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane.rb:33:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
[15:30:14]	[Step 1/1] /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:322:in `syswrite': Broken pipe (Errno::EPIPE)
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:322:in `do_write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:339:in `block in write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `each'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `inject'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:338:in `write'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:207:in `copy_stream'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:207:in `send_request_with_body_stream'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/generic_request.rb:125:in `exec'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1507:in `block in transport_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1479:in `request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1470:in `request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:87:in `perform_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/request/url_encoded.rb:15:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/request/multipart.rb:15:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:175:in `post'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:203:in `upload_build'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:193:in `run_release_upload'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-plugin-appcenter-1.8.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:297:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[15:30:14]	[Step 1/1] from extensions/AppCenterFastfile:7:in `block (2 levels) in parsing_binding'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane.rb:33:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[15:30:14]	[Step 1/1] from Fastfile:51:in `block (2 levels) in parsing_binding'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane.rb:33:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rvm/gems/ruby-2.6.3/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
[15:30:14]	[Step 1/1] from /Users/buildadmin/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
[15:30:14]	[Step 1/1] Process exited with code 1
[15:30:14]	[Step 1/1] Process exited with code 1
[15:30:14]	[Step 1/1] Step Command Line failed
```

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
