### ISSUE TITLE
undefined method `escape' for URI:Module

### ISSUE THREAD

**Issue by GeorgeIvanov** [microsoft/fastlane-plugin-appcenter#279]
```
/usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:958:in `add_new_app_to_distribution_group': \e[31m[!] undefined method `escape' for URI:Module\e[0m (NoMethodError)
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:335:in `block in add_app_to_distribution_group_if_needed'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:333:in `each'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:333:in `add_app_to_distribution_group_if_needed'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:355:in `run'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:217:in `uploadToAppCenter'
	from Fastfile:182:in `buildAndUploadToAppCenter'
	from Fastfile:70:in `block (2 levels) in parsing_binding'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/gems/fastlane-2.194.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.194.0/libexec/bin/fastlane:23:in `<main>'
```

**Comment by rewgoes** [comment]
@anywherepilot @sergei-fedorov @jp-andre 

Could you please check this issue and check this PR #287 ?

URI.escape was removed from Ruby 3.0.0: https://github.com/ruby/uri/issues/14

It is possible to add support to Ruby 3.+?

Related issues and PRs:
#283 
#287

**Comment by DmitriyKirakosyan** [comment]
The fix was merged and released, closing.
