### ISSUE TITLE
Uploading dsym fails with "Faraday::ConnectionFailed"

### ISSUE THREAD

**Issue by toby3105** [microsoft/fastlane-plugin-appcenter#93]
I'm currently unable to upload the dsym archive using the appcenter_upload action.
In my fastlane file I have
```
lane :uploadSymbols do |options|
	appcenter_upload(
		api_token: options[:token],
		owner_name: ENV["COMPANY_NAME"],
		app_name: ENV["APP_SLUG"],
		upload_dsym_only: true,
		dsym: "dsymToUpload.app.dSYM.zip",
		release_notes: "Latest development version",
		destinations:"Development"
	)
end
```
When I run
```
bundle exec fastlane uploadSymbols token:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --verbose
```
I get
```
/Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite': [!] Broken pipe (Faraday::ConnectionFailed)                                                               
from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
```

If I specify the app, it is able to upload the .ipa but it still fails while uploading the dsym archive.
The zip file is a bit big and I'm thinking that maybe the connection timesout but I would expect a different error message.
```
mac:UploadDsymTest myUser$ ls -l dsymToUpload.app.dSYM.zip                                   
-rw-------  1 myUser  staff  305927307 Jul  6 14:30 dsymToUpload.app.dSYM.zip
```
I've attached the `fastlane env` and the command output while using the `--verbose` flag. Any ideas?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.3                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.20.1 (Apple Git-117)   |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.14.3 (18D109)            |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | true                                 |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

before_all do
	update_fastlane
end
platform :ios do
	lane :uploadSymbols do |options|
		appcenter_upload(
			api_token: options[:token],
			owner_name: ENV["COMPANY_NAME"],
			app_name: ENV["APP_SLUG"],
			upload_dsym_only: true,
			dsym: "dsymToUpload.app.dSYM.zip",
			release_notes: "Latest development version",
			destinations:"Development"
		)
	end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
| fastlane-plugin-appcenter | 1.1.0        |
</details>

*generated on:* **2019-07-06**
</details>

<details><summary> Full command output </summary>

```

mac:fastlane myUser$ bundle exec fastlane uploadSymbols token:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --verbose
DEBUG [2019-07-06 18:58:54.87]: Checking if there are any plugins that should be loaded...
DEBUG [2019-07-06 18:58:54.98]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2019-07-06 18:58:54.99]: gem 'fastlane-plugin-appcenter' is already installed
+------------------------+---------+------------------+
|                    Used plugins                     |                                       
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-appce  | 1.1.0   | appcenter_upload |
| nter                   |         |                  |
+------------------------+---------+------------------+

DEBUG [2019-07-06 18:58:55.06]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
Successfully loaded Appfile at path '/Users/myUser/Work/Build/UploadDsymTest/fastlane/Appfile'-------
Successfully loaded Appfile at path '/Users/myUser/Work/Build/UploadDsymTest/fastlane/Appfile'-------
DEBUG [2019-07-06 18:58:55.07]: Using token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO [2019-07-06 18:58:55.09]: ------------------------------
INFO [2019-07-06 18:58:55.09]: --- Step: default_platform ---
INFO [2019-07-06 18:58:55.09]: ------------------------------                                 
INFO [2019-07-06 18:58:55.10]: Driving the lane 'ios uploadSymbols' 🚀                        
INFO [2019-07-06 18:58:55.11]: -----------------------------
INFO [2019-07-06 18:58:55.11]: --- Step: update_fastlane ---                                  
INFO [2019-07-06 18:58:55.11]: -----------------------------                                  
INFO [2019-07-06 18:58:55.11]: Looking for updates for fastlane...
INFO [2019-07-06 18:59:03.75]: Nothing to update ✅
INFO [2019-07-06 18:59:03.75]:
INFO [2019-07-06 18:59:03.75]: Please help us test early releases of fastlane by opting into nightly builds 🌃
INFO [2019-07-06 18:59:03.75]: Just replace your `update_fastlane` call with
INFO [2019-07-06 18:59:03.75]:
INFO [2019-07-06 18:59:03.75]: ▸ update_fastlane(nightly: true)                               
INFO [2019-07-06 18:59:03.75]:
INFO [2019-07-06 18:59:03.75]: Nightly builds are reviewed and tested just like the public releases 🚂
INFO [2019-07-06 18:59:03.75]:
INFO [2019-07-06 18:59:03.76]: ------------------------------                                 
INFO [2019-07-06 18:59:03.76]: --- Step: appcenter_upload ---                                 
INFO [2019-07-06 18:59:03.76]: ------------------------------                                 
INFO [2019-07-06 18:59:04.46]: Starting dSYM upload...
INFO [2019-07-06 18:59:05.01]: Uploading dSYM...
WARN [2019-07-06 19:03:15.30]: Lane Context:
INFO [2019-07-06 19:03:15.30]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios uploadSymbols"}
ERROR [2019-07-06 19:03:15.30]: Broken pipe                                                   
INFO [2019-07-06 19:03:15.31]: Successfully generated documentation at path '/Users/myUser/Work/Build/UploadDsymTest/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |                                                     
\+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | update_fastlane  | 8           |
| 💥   | appcenter_upload | 251         |                                                     
+------+------------------+-------------+

DEBUG [2019-07-06 19:03:15.32]: All plugins are up to date
ERROR [2019-07-06 19:03:15.32]: fastlane finished with errors                                 
Looking for related GitHub issues on fastlane/fastlane...
Search query: Broken pipe

URL: https://api.github.com/search/issues?q=Broken%20pipe+repo:fastlane/fastlane
➡️  Broken pipe for upload binary to Hockeyapp
    https://github.com/fastlane/fastlane/issues/14699 [closed] 47 💬                              3 days ago

➡️  Broken pipe for upload binary to Hockeyapp                                                   
https://github.com/fastlane/fastlane/issues/14698 [closed] 0 💬                               5 days ago

➡️  Transporter transfer failed: Broken pipe                                                     
https://github.com/fastlane/fastlane/issues/13569 [closed] 2 💬                               22 Dec 2018

and 22 more at: https://github.com/fastlane/fastlane/search?q=Broken%20pipe&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2019-07-06 19:03:16.01]: All plugins are up to date
/Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite': [!] Broken pipe (Faraday::ConnectionFailed)                                                               
from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1411:in `catch'            
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1384:in `request'          
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:853:in `start'             
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1375:in `request'          
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'           
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `put'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-appcenter-1.1.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:157:in `upload_symbol'            
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-appcenter-1.1.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:61:in `run_dsym_upload'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-appcenter-1.1.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:205:in `run'              
		from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        from Fastfile:8:in `block (2 levels) in parsing_binding'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /Users/myUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
        from /Users/myUser/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/myUser/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
</details>

**Comment by DennisPan** [comment]
@toby3105 Is this a persistent issue or intermittent? I searched the error message, and found this might be something worth trying: https://stackoverflow.com/a/25168422. Could you give that a try? If you need assistance, feel free to reach out to support via App Center portal.

**Comment by toby3105** [comment]
@DennisPan Yes this happens every time, on different machines with different versions of macOS. I'll try what's suggested on SO but I'm not sure it going to have any effect considering that it's able to upload the .ipa and only the dsym archive fails. Will updated the post when I've got a bit more info.

**Comment by toby3105** [comment]
@DennisPan After a bit more investigation I think I've been able to find the issue
> The symbol uploads API will not work for symbols files that are 256MB or larger in size. Please use the App Center CLI to upload these files. You can install the App Center CLI by following the instructions in our App Center CLI repo. [[source](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication)]

Our dsym is arround 300MB

Knowing this I believe that it would be better to either allow the user the option to just upload the .ipa currently the .dsym is uploaded automatically if it matches the name of the .ipa and is in the same folder. Or check the size of the .dsym and throw and e more human readable error. Ideally both.

**Comment by DennisPan** [comment]
@toby3105 Thanks for finding that! Makes sense. Let me take a look at what it takes to have similar support on fastlane side as what we have on CLI. If too much, then I agree we should have an option to skip .dsym when we don't support large file.

**Comment by adityakhatkhate** [comment]
We are running into this same error. I was wondering if there a reason for putting in the limitation on the plugin given the app center cli does not have such a limitation ?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
